### ISSUE TITLE
Duplicate class name

### ISSUE THREAD

**Issue by juniwalk** [ublaboo/datagrid#111]
There are to same classes in two files, composer alerts me with error.

[DataGridHasToBeAttachedToPresenterComponentException.php
](https://github.com/ublaboo/datagrid/tree/master/src/Exception)
[DataGridException.php
](https://github.com/ublaboo/datagrid/blob/master/src/Exception/DataGridHasToBeAttachedToPresenterComponentException.php)

**Comment by paveljanda** [comment]
It should be fixed in master, can you test it please?

**Comment by juniwalk** [comment]
Composer still throws error:

`Warning: Ambiguous class resolution, "Ublaboo\DataGrid\Exception\DataGridException" was found in both "/project/vendor/ublaboo/datagrid/src/Exception/DataGridException.php" and "/project/vendor/ublaboo/datagrid/src/Exception/DataGridHasToBeAttachedToPresenterComponentException.php", the first will be used.
`

**Comment by paveljanda** [comment]
Are you using dev-master or a tagged version?

**Comment by juniwalk** [comment]
When I post this issue I had `^2.0` secodn comment is from `dev-master`.

**Comment by juniwalk** [comment]
Fixed, it just took some time till packagist got the latest commit.

**Comment by paveljanda** [comment]
Ok, i will tag it as 2.0.5
